// src/app/layout.tsx
import { ReactNode } from 'react';
import { NavBar } from "@/components/navbar";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Head from "next/head";
import './globals.css';

interface RootLayoutProps {
    children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <>
            <Head>
                {/* Add your meta tags, CSS links, or any other elements you want in the head */}
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                {/* Add external CSS or JS files */}
                <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;700&display=swap" rel="stylesheet"/>
            </Head>
            {/* Remove the <html> and <body> tags */}
            <main className="antialiased max-w-2xl mb-40 flex flex-col md:flex-row mx-4 mt-8 lg:mx-auto">
                <NavBar/>
                {children}
                <Analytics/>
                <SpeedInsights/>
            </main>
        </>
    );
}

